# Generated by Django 6.0.1 on 2026-02-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_created_at_user_updated_at'),
        ('posts', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
    ]
