# Generated by Django 5.2.11 on 2026-02-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_author_alter_comment_author_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
