# Generated by Django 5.2.11 on 2026-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_post_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
